server:
  port: 1211

spring:
  datasource:
    username: root
    password: lzw990127
    url: jdbc:mysql://localhost:3306/ebook?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/mapping/*Mapper.xml